url: https://marcomortillaro.github.io
baseurl: 

# Site settings
title: Marco Mortillaro
email: marco.mortillaro.gd@gmail.com
description: "Marco Mortillaro Game Design Portfolio"



# Bio / About Section
people:
  - name: Marco Mortillaro
    pic: 1
    position: Game Designer
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/marcomortillaro/
      - title: github
        url: https://github.com/marcomortillaro
      - title: gamepad  # Icona perfetta per Itch.io o gaming
        url: https://marcomortillaro.itch.io/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
