url: https://marcomortillaro.github.io
baseurl: 

# Site settings
title: Marco Mortillaro | Lead Game Designer | Combat & Systems
email: marco.mortillaro.gd@gmail.com
description: "Portfolio of Marco Mortillaro, Lead Game Designer specialized in Combat Systems, 3Cs, and Action AAA/AA titles like Soulstice."

# Header settings
header:
  title: "MARCO MORTILLARO"
  phrase: "Lead/Senior Game Designer | Combat & 3Cs Specialist"
  button_text: "Download CV (PDF)"
  button_link: "Marco_Mortillaro_CV.pdf" # Assicurati che il nome del file sia identico a quello che carichi su GitHub

# Bio / About Section
people:
  - name: Marco Mortillaro
    pic: 1
    position: Lead/Senior Game Designer
    social:
      - title: linkedin
        url: https://www.linkedin.com/in/marcomortillaro/
      - title: twitter
        url: http://twitter.com/ziomorti

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
      - title: linkedin
        url: https://www.linkedin.com/in/marcomortillaro/
      - title: twitter
        url: http://twitter.com/ziomorti

# Postal address (add as many lines as necessary)
address:
  - line: xxx
  - line: xxx

# Build settings
markdown: kramdown
permalink: pretty
